# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''

imports:
    - { resource: '../src/Task/Presentation/Resources/config/services.yml' }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
            - '../src/Task/Application/Query'
            - '../src/Task/Application/Command'
            - '../src/Task/Domain/ValueObject'
            - '../src/Task/Domain/DTO'
            - '../src/Task/Domain/Event'
            - '../src/Task/Domain/Entity'


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
